### ISSUE TITLE
[TEST] 방 생성 테스트

### ISSUE THREAD

**Issue by orijoon98** [Kaleub/kaleub_back#27]
## 📌  Feature Issue

방 생성 테스트

## 📝  To-do

- [ ] 로그인 만료 확인
- [ ] 제목  예외 확인
- [ ] 비밀번호 예외 확인
- [ ] 정상적으로 생성되는지 확인
