### ISSUE TITLE
[TEST] 테스트 코드

### ISSUE THREAD

**Issue by orijoon98** [Kaleub/kaleub_back#50]
## 📌  Feature Issue

테스트 코드

## 📝  To-do

- [x] 기존 테스트코드 수정
- [x] auth 테스트코드 추가
- [x] feed 테스트코드 추가
