### ISSUE TITLE
[TEST] 테스트 코드

### ISSUE THREAD

**Issue by heyazoo1007** [Kaleub/kaleub_back#53]
## 📌  Feature Issue

테스트 코드
## 📝  To-do

- [x] auth 테스트 코드 추가
- [x] room 테스트 코드 추가
- [x] feed 테스트 코드 추가
